<?php
return [
	['date' => $year . '-02-14', 'name' => "Valentine's Day"],
	['date' => $year . '-03-08', 'name' => "International Women's Day"],
	['date' => $year . '-03-20', 'name' => "March Equinox"],
	['date' => $year . '-03-31', 'name' => "Daylight Saving Time starts"],
	['date' => $year . '-04-01', 'name' => "April Fools"],
	['date' => $year . '-04-28', 'name' => "Orthodox Easter Day"],
	['date' => $year . '-04-29', 'name' => "Orthodox Easter Day holiday"],
	['date' => $year . '-05-01', 'name' => "Labor Day"],
	['date' => $year . '-05-09', 'name' => "Victory Day / Memorial Day"],
	['date' => $year . '-05-12', 'name' => "Mother's Day"],
	['date' => $year . '-05-18', 'name' => "Europe Day"],
	['date' => $year . '-05-26', 'name' => "Kiev Day"],
	['date' => $year . '-06-16', 'name' => "Orthodox Pentecost"],
	['date' => $year . '-06-17', 'name' => "Orthodox Pentecost holiday"],
	['date' => $year . '-06-21', 'name' => "June Solstice"],
	['date' => $year . '-06-28', 'name' => "Constitution Day"],
	['date' => $year . '-07-07', 'name' => "Kupala Night"],
	['date' => $year . '-07-08', 'name' => "Family Day"],
	['date' => $year . '-07-28', 'name' => "Baptism of Kyivan Rus"],
	['date' => $year . '-08-24', 'name' => "Independence Day"],
	['date' => $year . '-08-26', 'name' => "Independence Day observed"],
	['date' => $year . '-09-23', 'name' => "September Equinox"],
	['date' => $year . '-10-06', 'name' => "Teacher's Day"],
	['date' => $year . '-10-14', 'name' => "Defenders' Day"],
	['date' => $year . '-10-27', 'name' => "Daylight Saving Time ends"],
	['date' => $year . '-11-21', 'name' => "Dignity and Freedom Day"],
	['date' => $year . '-12-06', 'name' => "Army Day"],
	['date' => $year . '-12-19', 'name' => "St. Nicholas Day"],
	['date' => $year . '-12-22', 'name' => "December Solstice"],
	['date' => $year . '-12-25', 'name' => "Catholic Christmas Day"],
];